<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $_helper = $this->helper('ForMage\FeederTheme\Helper\Data'); ?>
<?php $qty = $_helper->getProductQty($_product); ?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <?php if ($qty == 1) :?>
            <span><?= $block->escapeHtml(__('In stock 1 product', $qty)) ?></span>
        <?php endif; ?>
        <?php if ($qty > 1 && $qty <= 4) :?>
            <span><?= $block->escapeHtml(__('In stock %1 products', $qty)) ?></span>
        <?php endif; ?>
            <?php if ($qty > 4 && $qty <= 10) :?>
                <span><?= $block->escapeHtml(__('In stock %1 products2', $qty)) ?></span>
            <?php endif; ?>
        <?php if ($qty > 10) :?>
            <span><?= $block->escapeHtml(__('In stock above 10 products')) ?></span>
        <?php endif; ?>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
