<?php $_category = $block->getCategory(); ?>
<div id="<?= /* @escapeNotVerified */ $block->getElementId(); ?>" class="block block-products">
    <div class="block-title">
        <strong id="block-heading" role="heading"><?= /* @escapeNotVerified */ $this->getTitle(); ?></strong>
        <a href="<?= /* @escapeNotVerified */ $_category->getUrl(); ?>"><?= /* @escapeNotVerified */ __('View All'); ?></a>
        <span class="nav">
             <i class='icon-play3 slick-arrow arrow-prev slick-disabled' aria-disabled="true" style="display:inline;"></i>
             <i class='icon-play slick-arrow arrow-next' style="display:inline;"></i>
        </span>
    </div>
    <div class="block-content slick-slider">
        <?php if (!$block->getAjax()) : ?>
            <?= /* @escapeNotVerified */ $block->getProducts($_category)->toHtml(); ?>
        <?php endif; ?>
    </div>
</div>

<script type="text/x-magento-init">
        {
            "#<?= /* @escapeNotVerified */ $block->getElementId(); ?> .block-content":
            {
                "productCarousel":
                {
                    "delay": true,
                    "prevArrow": ".promotions .arrow-prev",
                    "nextArrow": ".promotions .arrow-next",
                    "category_id": "<?= /* @escapeNotVerified */ $_category->getId(); ?>",
                    "children": "",
                    "slick": {
                        "appendArrows": "#<?= /* @escapeNotVerified */ $block->getElementId(); ?> .block-title .nav",
                        "infinite": false,
                        "prevArrow": "<i class='icon-play3'></i>",
                        "nextArrow": "<i class='icon-play'></i>",
                        "responsive": [
                        {
                                "breakpoint": 1280,
                                "settings": {
                                    "slidesToShow": <?= /* @escapeNotVerified */ $block->getItems(); ?>,
                                    "slidesToScroll": <?= (bool)$block->getScroll() ?/* @escapeNotVerified */ $block->getItems() : 1; ?>
                                }
                            },
                            {
                                "breakpoint": 1024,
                                "settings": {
                                    "slidesToShow": 3,
                                    "slidesToScroll": <?= (bool)$block->getScroll() ? 4 : 1; ?>
                                }
                            },
                            {
                                "breakpoint": 640,
                                "settings": {
                                    "slidesToShow": 2,
                                    "slidesToScroll": <?= (bool)$block->getScroll() ? 4 : 1; ?>
                                }
                            },
                            {
                                "breakpoint": 1,
                                "settings": {
                                    "slidesToShow": 1,
                                    "slidesToScroll": <?= (bool)$block->getScroll() ? 1 : 1; ?>
                                }
                            }
                        ]
                    }
                }
            }
        }
</script>