<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper">
            <?php foreach ($_additional as $_data): ?>
                <div class="attribute <?= $block->escapeHtml(__($_data['code'])) ?>">
                    <span class="label" scope="row"><?= $block->escapeHtml(__($_data['label'])) ?>:</span>
                    <span class="col data" data-th="<?= $block->escapeHtml(__($_data['label'])) ?>"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></span>
                </div>
            <?php endforeach; ?>
    </div>
<?php endif;?>
