<?php
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile
?>
<?php

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    $_helper = $this->helper('ForMage\FeederTheme\Helper\Data');

}
?>

<?php if ($exist):?>
    <?php $iterator = 1; ?>
    <i class="icon-play3 slick-prev slick-arrow" aria-disabled="false" style="display: block;"></i>
    <?php foreach ($items as $_item): ?>
        <div class="product-item slick-slide">
            <div class="product-item-info">

                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                        <?= $block->getImage($_item, $image)->toHtml() ?>
                    </a>

                <div class="review">
                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <div data-role="add-to-links" class="actions-secondary">
                        <?php if ($block->getAddToCompareUrl() && $showCompare) :?>
                            <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                            <a href="#" class="action tocompare"
                               data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                               title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                            </a>
                        <?php endif; ?>
                        <div class="labels">
                            <?php if ($_helper->hasSpecialPrice($_item)): ?>
                                <span class="promo label" title="<?php /* @escapeNotVerified */ echo __('Promotion') ?>"><?php /* @escapeNotVerified */ echo __('Promotion') ?></span>
                            <?php endif; ?>
                            <?php if ($_helper->isNew($_item)): ?>
                                <span class="label new" title="<?php /* @escapeNotVerified */ echo __('New') ?>"><?php /* @escapeNotVerified */ echo __('New') ?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                    <strong class="product name product-item-name">
                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"
                           class="product-item-link">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>

                    <div class="product-item-details">

                        <div class="product-item-inner">
                            <?php echo $block->getProductPriceHtml($_item, $type);  ?>

                            <?php if ($showCart): ?>
                                <div class="product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary"
                                                            data-mage-init='{"redirectUrl":{"url":"<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form class="product_addtocart_form" data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_item->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <input type="hidden" name="form_key" value="<?= /* @escapeNotVerified */ $block->getFormKey() ?>">
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
            </div>
        </div>
        <?php $iterator++; ?>
    <?php endforeach ?>
    <i class="icon-play slick-next slick-arrow" style="display: block;" ></i>
<?php endif;?>