<?php
// @codingStandardsIgnoreFile
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $id = '#mm' . rand(10, 500) ?>
<nav class="navigation">
    <ul id="<?= /* @escapeNotVerified */ $id ?>" class="custom-menu">
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
